# Plugins
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Congresso Estadual da Ordem DeMolay - Piauí"
email: "ceodpi@demolaypi.org.br"
description: "Congresso Estadual da Ordem DeMolay - Piauí"
baseurl: ""
url: "https://ceod.demolaypi.org.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GCE-PI"
organizerAlternateName: "Grande Capítulo do Estado do Piauí"
organizerDescription: "GCE"
organizerEmail: "ceodpi@demolaypi.org.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://demolaypi.org.br"

# Navigation
navigationLinks:
 - {permalink: "#", text: "Home"}
 - {permalink: "#cronograma", text: "Cronograma"}
 - {permalink: "#inscreva-se", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout> | Jaicós-PI, 2017"
eventDate: "8 e 9 de dezembro, 2017"
typeoutTextValues: '"", "CEOD Piauí", "Amor Filial", "Reverência Pelas Coisas Sagradas", "Cortesia", "Companheirismo", "Fidelidade", "Pureza", "Patriotismo"'
typeoutFallback: "CEOD"
heroButtons:
 - {link: "#inscreva-se", text: "Inscreva-se"}
